# Generated by Django 2.1 on 2018-08-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportLogValues',
            new_name='ReportLogValue',
        ),
    ]
