# Generated by Django 2.1 on 2018-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180821_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
