# Generated by Django 2.1 on 2018-08-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180822_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNetworkSpeedReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.Report')),
                ('category', models.CharField(max_length=30, null=True)),
                ('ping', models.IntegerField()),
                ('download', models.IntegerField()),
                ('upload', models.IntegerField()),
            ],
            bases=('report.report',),
        ),
        migrations.AddField(
            model_name='applicationlogreport',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
