# Generated by Django 2.1 on 2018-08-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogreport',
            name='report_ptr',
        ),
        migrations.RemoveField(
            model_name='appreport',
            name='report_ptr',
        ),
        migrations.RemoveField(
            model_name='officenetworkspeedreport',
            name='report_ptr',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='ApplicationLogReport',
        ),
        migrations.DeleteModel(
            name='AppReport',
        ),
        migrations.DeleteModel(
            name='OfficeNetworkSpeedReport',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
