# Generated by Django 2.1 on 2018-08-26 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0009_auto_20180826_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLogReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=30, null=True)),
                ('info', models.IntegerField()),
                ('warn', models.IntegerField()),
                ('error', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('login', models.BooleanField()),
                ('recharge', models.BooleanField()),
                ('wallet', models.BooleanField()),
                ('earn', models.BooleanField()),
                ('gem', models.BooleanField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeNetworkSpeedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=30, null=True)),
                ('ping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('download', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('upload', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
