# Generated by Django 2.1 on 2018-08-26 05:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0010_applicationlogreport_appreport_officenetworkspeedreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppReport',
            new_name='App',
        ),
        migrations.RenameModel(
            old_name='ApplicationLogReport',
            new_name='ApplicationLog',
        ),
        migrations.RenameModel(
            old_name='OfficeNetworkSpeedReport',
            new_name='OfficeNetworkSpeed',
        ),
    ]
