# Generated by Django 2.1 on 2018-08-26 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20180826_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='target_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='target_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officenetworkspeed',
            name='target_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
