# Generated by Django 2.1 on 2018-09-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20180826_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlog',
            name='category',
        ),
    ]
