# Generated by Django 2.1 on 2018-09-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0013_remove_applicationlog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('target_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('WAN_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('WAN_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('port15_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('port15_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('port16_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('port16_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('p2p_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('p2p_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('wfd_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('wfd_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
