# Generated by Django 2.1 on 2018-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='document',
            field=models.ImageField(upload_to='static/documents/%Y/%m/%d/'),
        ),
    ]
