# Generated by Django 2.1 on 2018-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20180918_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='document',
            field=models.ImageField(upload_to='media/documents/%Y/%m/%d/'),
        ),
    ]
