# Generated by Django 2.1 on 2018-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20180918_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='document',
            field=models.ImageField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
