# Generated by Django 2.1 on 2018-10-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'category'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Code'),
        ),
    ]
